"""
PDF Report Generator for MetaQuant Nigeria.
Generates daily market summary reports in PDF format.
"""

from datetime import datetime
from typing import Dict, List, Any, Optional
import os
import logging

logger = logging.getLogger(__name__)

# Try importing PDF library - no warning at module level
try:
    from reportlab.lib import colors
    from reportlab.lib.pagesizes import A4, letter
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.units import inch, cm
    from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, Image
    from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
    REPORTLAB_AVAILABLE = True
except ImportError:
    REPORTLAB_AVAILABLE = False
    # Don't log warning at import time - let calling code handle it


class ReportGenerator:
    """Generate PDF market reports."""
    
    def __init__(self, db=None):
        self.db = db
        self.styles = None
        if REPORTLAB_AVAILABLE:
            self._setup_styles()
    
    def _setup_styles(self):
        """Setup PDF styles."""
        self.styles = getSampleStyleSheet()
        
        # Custom styles
        self.styles.add(ParagraphStyle(
            name='ReportTitle',
            parent=self.styles['Heading1'],
            fontSize=24,
            spaceAfter=30,
            alignment=TA_CENTER,
            textColor=colors.HexColor('#1a5f7a')
        ))
        
        self.styles.add(ParagraphStyle(
            name='SectionHeader',
            parent=self.styles['Heading2'],
            fontSize=14,
            spaceBefore=20,
            spaceAfter=10,
            textColor=colors.HexColor('#2c3e50')
        ))
        
        self.styles.add(ParagraphStyle(
            name='SubHeader',
            parent=self.styles['Heading3'],
            fontSize=11,
            spaceBefore=10,
            spaceAfter=5,
            textColor=colors.HexColor('#34495e')
        ))
    
    def generate_daily_summary(
        self,
        output_path: str,
        snapshot: Dict[str, Any],
        stocks_list: List[Dict],
        sector_rankings: List[Dict] = None,
        smart_money_data: Dict = None
    ) -> bool:
        """
        Generate a daily market summary PDF.
        
        Args:
            output_path: Path to save the PDF
            snapshot: Market snapshot data
            stocks_list: List of all stocks with data
            sector_rankings: Optional sector performance data
            smart_money_data: Optional smart money signals
            
        Returns:
            True if successful, False otherwise
        """
        if not REPORTLAB_AVAILABLE:
            logger.error("reportlab not installed. Cannot generate PDF.")
            return False
        
        try:
            doc = SimpleDocTemplate(
                output_path,
                pagesize=A4,
                rightMargin=50,
                leftMargin=50,
                topMargin=50,
                bottomMargin=50
            )
            
            story = []
            
            # Title
            story.append(Paragraph("MetaQuant Nigeria", self.styles['ReportTitle']))
            story.append(Paragraph(
                f"Daily Market Summary - {datetime.now().strftime('%B %d, %Y')}",
                self.styles['SubHeader']
            ))
            story.append(Spacer(1, 20))
            
            # Market Overview Section
            story.append(Paragraph("Market Overview", self.styles['SectionHeader']))
            story.extend(self._create_market_overview(snapshot))
            
            # Top Movers Section
            story.append(Paragraph("Top Movers", self.styles['SectionHeader']))
            story.extend(self._create_top_movers(snapshot, stocks_list))
            
            # Sector Performance Section
            if sector_rankings:
                story.append(Paragraph("Sector Performance", self.styles['SectionHeader']))
                story.extend(self._create_sector_table(sector_rankings))
            
            # Volume Leaders Section
            story.append(Paragraph("Volume Leaders", self.styles['SectionHeader']))
            story.extend(self._create_volume_leaders(stocks_list))
            
            # Smart Money Signals (if available)
            if smart_money_data:
                story.append(Paragraph("Smart Money Signals", self.styles['SectionHeader']))
                story.extend(self._create_smart_money_section(smart_money_data))
            
            # Footer
            story.append(Spacer(1, 30))
            story.append(Paragraph(
                f"Generated by MetaQuant Nigeria at {datetime.now().strftime('%H:%M:%S')}",
                ParagraphStyle(name='Footer', fontSize=8, alignment=TA_CENTER, textColor=colors.gray)
            ))
            
            # Build PDF
            doc.build(story)
            logger.info(f"PDF report generated: {output_path}")
            return True
            
        except Exception as e:
            logger.error(f"Error generating PDF: {e}")
            return False
    
    def _create_market_overview(self, snapshot: Dict) -> List:
        """Create market overview section."""
        elements = []
        
        gainers = snapshot.get('gainers', 0)
        losers = snapshot.get('losers', 0)
        total = snapshot.get('total_stocks', 0)
        unchanged = total - gainers - losers
        
        # Calculate health score
        health_score = ((gainers - losers) / total * 50 + 50) if total > 0 else 50
        
        if health_score >= 60:
            sentiment = "Bullish"
        elif health_score >= 40:
            sentiment = "Neutral"
        else:
            sentiment = "Bearish"
        
        data = [
            ['Metric', 'Value'],
            ['Total Stocks', str(total)],
            ['Gainers', f"{gainers} ({gainers/total*100:.1f}%)" if total > 0 else "0"],
            ['Losers', f"{losers} ({losers/total*100:.1f}%)" if total > 0 else "0"],
            ['Unchanged', str(unchanged)],
            ['Market Health', f"{health_score:.0f}/100"],
            ['Sentiment', sentiment],
        ]
        
        table = Table(data, colWidths=[150, 200])
        table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1a5f7a')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, 0), 11),
            ('BOTTOMPADDING', (0, 0), (-1, 0), 10),
            ('BACKGROUND', (0, 1), (-1, -1), colors.HexColor('#f8f9fa')),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#dee2e6')),
            ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor('#f8f9fa')]),
        ]))
        
        elements.append(table)
        elements.append(Spacer(1, 15))
        
        return elements
    
    def _create_top_movers(self, snapshot: Dict, stocks_list: List[Dict]) -> List:
        """Create top gainers/losers tables."""
        elements = []
        
        # Top Gainers
        elements.append(Paragraph("Top Gainers", self.styles['SubHeader']))
        
        gainers = snapshot.get('top_gainers', [])[:5]
        if gainers:
            data = [['Symbol', 'Price', 'Change']]
            for g in gainers:
                data.append([
                    g.get('symbol', '?'),
                    f"N{g.get('price', 0):,.2f}",
                    f"+{g.get('change', 0):.2f}%"
                ])
            
            table = Table(data, colWidths=[100, 100, 80])
            table.setStyle(self._get_table_style(header_color='#27ae60'))
            elements.append(table)
        else:
            elements.append(Paragraph("No gainers data available", self.styles['Normal']))
        
        elements.append(Spacer(1, 10))
        
        # Top Losers
        elements.append(Paragraph("Top Losers", self.styles['SubHeader']))
        
        losers = snapshot.get('top_losers', [])[:5]
        if losers:
            data = [['Symbol', 'Price', 'Change']]
            for l in losers:
                data.append([
                    l.get('symbol', '?'),
                    f"N{l.get('price', 0):,.2f}",
                    f"{l.get('change', 0):.2f}%"
                ])
            
            table = Table(data, colWidths=[100, 100, 80])
            table.setStyle(self._get_table_style(header_color='#e74c3c'))
            elements.append(table)
        else:
            elements.append(Paragraph("No losers data available", self.styles['Normal']))
        
        elements.append(Spacer(1, 15))
        
        return elements
    
    def _create_sector_table(self, sector_rankings: List[Dict]) -> List:
        """Create sector performance table."""
        elements = []
        
        data = [['Sector', '1D', '1W', '1M', 'Stocks']]
        
        for sr in sector_rankings[:10]:
            data.append([
                sr.get('sector', '?')[:15],
                f"{sr.get('avg_1d', 0):+.1f}%",
                f"{sr.get('avg_1w', 0):+.1f}%",
                f"{sr.get('avg_1m', 0):+.1f}%",
                str(sr.get('count', 0))
            ])
        
        table = Table(data, colWidths=[120, 60, 60, 60, 50])
        table.setStyle(self._get_table_style())
        elements.append(table)
        elements.append(Spacer(1, 15))
        
        return elements
    
    def _create_volume_leaders(self, stocks_list: List[Dict]) -> List:
        """Create volume leaders table."""
        elements = []
        
        # Sort by volume
        sorted_stocks = sorted(stocks_list, key=lambda x: x.get('volume', 0) or 0, reverse=True)[:10]
        
        data = [['Symbol', 'Volume', 'RVOL', 'Change']]
        
        for s in sorted_stocks:
            vol = s.get('volume', 0) or 0
            rvol = s.get('rvol', 1) or 1
            chg = s.get('change', 0) or 0
            
            data.append([
                s.get('symbol', '?'),
                f"{vol:,.0f}",
                f"{rvol:.1f}x",
                f"{chg:+.2f}%"
            ])
        
        table = Table(data, colWidths=[100, 100, 60, 70])
        table.setStyle(self._get_table_style())
        elements.append(table)
        elements.append(Spacer(1, 15))
        
        return elements
    
    def _create_smart_money_section(self, smart_money_data: Dict) -> List:
        """Create smart money signals section."""
        elements = []
        
        # Accumulation signals
        acc = smart_money_data.get('accumulation', [])[:5]
        if acc:
            elements.append(Paragraph("Accumulation Signals", self.styles['SubHeader']))
            data = [['Symbol', 'Score', 'Strength']]
            for a in acc:
                data.append([
                    a.get('symbol', '?'),
                    f"{a.get('score', 0):.1f}",
                    a.get('strength', 'N/A')
                ])
            table = Table(data, colWidths=[100, 80, 100])
            table.setStyle(self._get_table_style(header_color='#27ae60'))
            elements.append(table)
            elements.append(Spacer(1, 10))
        
        # Distribution signals
        dist = smart_money_data.get('distribution', [])[:5]
        if dist:
            elements.append(Paragraph("Distribution Signals", self.styles['SubHeader']))
            data = [['Symbol', 'Score', 'Strength']]
            for d in dist:
                data.append([
                    d.get('symbol', '?'),
                    f"{d.get('score', 0):.1f}",
                    d.get('strength', 'N/A')
                ])
            table = Table(data, colWidths=[100, 80, 100])
            table.setStyle(self._get_table_style(header_color='#e74c3c'))
            elements.append(table)
        
        return elements
    
    def _get_table_style(self, header_color='#1a5f7a'):
        """Get standard table style."""
        return TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor(header_color)),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, 0), 10),
            ('FONTSIZE', (0, 1), (-1, -1), 9),
            ('BOTTOMPADDING', (0, 0), (-1, 0), 8),
            ('TOPPADDING', (0, 1), (-1, -1), 5),
            ('BOTTOMPADDING', (0, 1), (-1, -1), 5),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#dee2e6')),
            ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor('#f8f9fa')]),
        ])
